GET http://localhost:3001/products

###

GET http://localhost:3001/products/6409025507f90ce9c1d43861


###

POST http://localhost:3001/products
Content-Type: application/json

{
}
  

###

DELETE http://localhost:3001/products/640f68b2d4fadd1070d282c2

###

PATCH http://localhost:3001/products/640f6f84defc789d430025b9
Content-Type: application/json

{
    "url": ""
}