GET http://localhost:3001/users

###

GET http://localhost:3001/users/6409025507f90ce9c1d43861


###

POST http://localhost:3001/users
Content-Type: application/json

{
    "username": "dsSarah",
    "password": "dogs",
    "contact": "sarahlovesdogs@yahoo.com"
}

###

DELETE http://localhost:3001/users/64091003b23e1850148cf990

###

PATCH http://localhost:3001/users/6409052b304fd991b557097e
Content-Type: application/json

{
    "username": "dsChanty"
}